name: Build and push new docker image

on:
  push:
    paths:
      - 'release-versions/*'
  workflow_dispatch:


jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Get latest version
        id: version
        run: |
          our_release=$(<release-versions/VERSION)
          echo "Our version = $our_release"
          main_version=$(echo $our_release | cut -d '-' -f1)
          echo "Main version = $main_version" 
          echo "NEW_VERSION=$our_release" >> $GITHUB_ENV
          echo "MAIN_VERSION=$main_version" >> $GITHUB_ENV

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Create lower-case owner name
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          echo "GH_OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Build and push image to docker hub
        uses: docker/build-push-action@v3
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:latest
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:${{ env.NEW_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:${{ env.MAIN_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:version-${{ env.MAIN_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:amd64-${{ env.NEW_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:amd64-${{ env.MAIN_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:amd64-version-${{ env.MAIN_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/docker-swag-msmtp:amd64-latest
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:latest
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:${{ env.NEW_VERSION }}
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:${{ env.MAIN_VERSION }}
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:version-${{ env.MAIN_VERSION }}
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:amd64-${{ env.NEW_VERSION }}
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:amd64-${{ env.MAIN_VERSION }}
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:amd64-version-${{ env.MAIN_VERSION }}
            ghcr.io/${{ env.GH_OWNER_LC }}/docker-swag-msmtp:amd64-latest
